"""Preset reminder lines for the maid (腹黑反差 placeholder voice).

These are scripted (non-SDK) — fired by ReminderScheduler at a fixed cadence,
not generated by a model. Replace / extend freely. The real personality will
flow from Claude's system prompt in stage 2; these placeholders just exercise
the speech-bubble plumbing.
"""

WATER_REMINDER_LINES = [
    "水喝够了吗？血液太黏稠程序会跑得慢哦。",
    "提醒一下：人类是需要喝水的生物，这是科学。",
]

ACTIVITY_REMINDER_LINES = [
    "已经坐了好一会了——再不站起来，你的关节会比我老得快。",
    "颈椎说它想休息。它说的，不是我。",
    "凝视屏幕这么久竟然还没爆炸，真是辛苦你了。看看远处。",
    "肩膀僵了吗？我可没有这种烦恼，转转吧。",
]

REMINDER_LINES = [
    *WATER_REMINDER_LINES,
    *ACTIVITY_REMINDER_LINES,
]
