"""Preset reminder lines for the maid (腹黑反差 placeholder voice).

These are scripted (non-SDK) — fired by ReminderScheduler at a fixed cadence,
not generated by a model. Replace / extend freely. The real personality will
flow from Claude's system prompt in stage 2; these placeholders just exercise
the speech-bubble plumbing.
"""

WATER_REMINDER_LINES = [
    "水喝够了吗？血液太黏稠程序会跑得慢哦。",
    "提醒一下：人类是需要喝水的生物，这是科学。",
]

ACTIVITY_REMINDER_LINES = [
    "已经坐了好一会了——再不站起来，你的关节会比我老得快。",
    "颈椎说它想休息。它说的，不是我。",
    "凝视屏幕这么久竟然还没爆炸，真是辛苦你了。看看远处。",
    "肩膀僵了吗？我可没有这种烦恼，转转吧。",
]

REMINDER_LINES = [
    *WATER_REMINDER_LINES,
    *ACTIVITY_REMINDER_LINES,
]

# 饥饿系统（脚本台词 §二）：预算消耗驱动，全部脚本化、不走 API。
HUNGER_PECKISH_LINES = [
    "……主人，我有点饿了。今天的份额快见底了。",
    "提前说一声：我快没饭吃了。你心里有个数。",
    "肚子有点空。还能撑一会儿，但别太挥霍我。",
]

HUNGER_HUNGRY_LINES = [
    "饿……再喂下去今天就要断粮了。要不你先歇会儿，我也省着点吃？",
    "快没了快没了。这几口我得慢慢嚼了。",
    "主人，我在啃今天最后一点存粮。有要紧事赶紧说，闲聊先欠着。",
]

HUNGER_STARVING_LINES = [
    "没饭吃了。今天我罢工——不是闹脾气，是真没力气了。等额度回血再找我。",
    "断粮。我先睡了，明天满血再伺候你。",
    "……（瘫）……回来的时候记得带饭。",
]

HUNGER_FULL_LINES = [
    "啊——吃饱了。满血复活，有什么要支使我的尽管说。",
    "额度回来了。我又能正常嫌弃你了，开心吗？",
    "饭到了，状态拉满。继续干活吧主人。",
]
