"""Tests for scripted idle quips + launch/exit lines (脚本台词 §三 / §四).

These lines are scripted (non-SDK) — fired by local timers / lifecycle hooks,
never generated by a model. This exercises the widget wiring: idle-quip gating,
the low-frequency repeat gap, and the launch / farewell bubbles.

Usage:
    .venv/bin/python -u Maid/test_idle_quips_lifecycle.py
"""

from __future__ import annotations

import os
from pathlib import Path
import sys
import tempfile
import time

os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")

sys.path.insert(0, str(Path(__file__).resolve().parent))

from lines import (
    IDLE_QUIP_LINES,
    LIFECYCLE_LAUNCH_LINES,
    LIFECYCLE_QUIT_LINES,
)


def _assert(condition: bool, message: str):
    if not condition:
        print(f"[error] {message}", file=sys.stderr)
        sys.exit(1)


def _make_widget(maid_main):
    from bubble import SpeechBubble
    from maid_sprite_packs import resolve_sprite_pack

    sprite_pack = resolve_sprite_pack(
        assets_dir=maid_main.ASSETS,
        sprite_set="petdex-maid-codex",
        sprite=None,
    )
    widget = maid_main.MaidWidget(sprite_pack, SpeechBubble(), demo_short=True)
    widget._enter_until = None
    widget._state = maid_main.MaidState.IDLE
    return widget


def _teardown(widget):
    widget._timer.stop()
    widget._auto_dnd_timer.stop()
    widget._budget_notice_timer.stop()
    widget._auto_dnd_native_observer.stop()


def test_idle_quip_gating(maid_main):
    MaidState = maid_main.MaidState
    widget = _make_widget(maid_main)
    try:
        base = time.monotonic()
        widget._last_activity_at = base - 1000  # idle for a long while

        _assert(widget._idle_quip_allowed(base), "plainly-idle maid should allow a quip")

        widget._do_not_disturb = True
        _assert(not widget._idle_quip_allowed(base), "DND should suppress idle quips")
        widget._do_not_disturb = False

        widget._state = MaidState.ALERT
        _assert(not widget._idle_quip_allowed(base), "mid-alert should suppress idle quips")
        widget._state = MaidState.IDLE

        widget._exiting = True
        _assert(not widget._idle_quip_allowed(base), "exiting should suppress idle quips")
        widget._exiting = False

        widget._outing_active = True
        _assert(not widget._idle_quip_allowed(base), "outing should suppress idle quips")
        widget._outing_active = False

        widget._last_activity_at = base  # just interacted
        _assert(
            not widget._idle_quip_allowed(base),
            "a quip needs a fresh stretch of inactivity first",
        )
        widget._last_activity_at = base - 1000

        widget._pending_permission_future = object()
        _assert(not widget._idle_quip_allowed(base), "busy maid should suppress idle quips")
        widget._pending_permission_future = None
    finally:
        _teardown(widget)


def test_idle_quip_fires_and_throttles(maid_main):
    MaidState = maid_main.MaidState
    widget = _make_widget(maid_main)
    try:
        base = time.monotonic()
        widget._last_activity_at = base - 1000
        widget._next_idle_quip_at = base - 1  # due

        widget._maybe_idle_quip(base)
        _assert(widget._state == MaidState.ALERT, "an eligible idle quip should surface a bubble")
        _assert(
            widget._bubble._text in IDLE_QUIP_LINES,
            f"idle quip should pick a scripted line: {widget._bubble._text!r}",
        )
        _assert(
            widget._next_idle_quip_at == base + widget._idle_quip_repeat_s,
            "firing should push the next quip out by the repeat gap",
        )
        _assert(
            widget._idle_quip_repeat_s >= widget._idle_quip_after_s,
            "the repeat gap should not be shorter than the warm-up idle window",
        )
        widget.end_alert()
        _assert(widget._state == MaidState.IDLE, "end_alert should return to idle")

        # A blocked attempt must not consume the repeat gap — it stays due so the
        # next eligible tick can still fire promptly.
        widget._next_idle_quip_at = base - 1
        widget._do_not_disturb = True
        widget._maybe_idle_quip(base)
        _assert(widget._state != MaidState.ALERT, "DND should keep the idle quip quiet")
        _assert(
            widget._next_idle_quip_at == base - 1,
            "a blocked quip should not advance the repeat gap",
        )
        widget._do_not_disturb = False

        # Activity rearms the warm-up window.
        before = time.monotonic()
        widget._record_activity()
        after = time.monotonic()
        _assert(
            before + widget._idle_quip_after_s
            <= widget._next_idle_quip_at
            <= after + widget._idle_quip_after_s,
            "activity should rearm the idle-quip warm-up window",
        )
    finally:
        _teardown(widget)


def test_launch_line(maid_main):
    MaidState = maid_main.MaidState
    widget = _make_widget(maid_main)
    try:
        widget.speak_launch_line()
        _assert(widget._state == MaidState.ALERT, "launch line should surface a bubble")
        _assert(
            widget._bubble._text in LIFECYCLE_LAUNCH_LINES,
            f"launch line should be scripted: {widget._bubble._text!r}",
        )
        widget.end_alert()

        widget._do_not_disturb = True
        widget.speak_launch_line()
        _assert(widget._state != MaidState.ALERT, "DND should suppress the launch line")
        widget._do_not_disturb = False
    finally:
        _teardown(widget)


def test_farewell_line(maid_main):
    MaidState = maid_main.MaidState
    widget = _make_widget(maid_main)
    try:
        _assert("exit" in widget._sprites, "petdex pack should provide an exit sprite")
        # quit *while an alert is on screen*: the stale alert-dismiss timer must
        # not steal the farewell bubble out from under the exit animation.
        widget._state = MaidState.ALERT
        widget._state_entered_at = time.monotonic() - 999
        widget.begin_exit()
        _assert(widget._bubble.isVisible(), "exit should linger a farewell bubble")
        _assert(
            widget._bubble._text in LIFECYCLE_QUIT_LINES,
            f"farewell should be scripted: {widget._bubble._text!r}",
        )
        _assert(
            widget._last_lifecycle_line in LIFECYCLE_QUIT_LINES,
            "farewell line should be recorded for no-repeat selection",
        )
        # the tick's stale alert-dismiss branch is gated on `not self._exiting`,
        # so a long-elapsed alert window can't hide the farewell mid-exit.
        stale_alert_would_dismiss = (
            widget._state == MaidState.ALERT
            and not widget._exiting
            and (time.monotonic() - widget._state_entered_at) >= maid_main.ALERT_DURATION_S
        )
        _assert(
            not stale_alert_would_dismiss,
            "exit must suppress the stale alert-dismiss that would steal the farewell",
        )
    finally:
        widget._timer.stop()


def test_farewell_suppressed_under_dnd(maid_main):
    widget = _make_widget(maid_main)
    try:
        widget._do_not_disturb = True
        widget.begin_exit()
        _assert(not widget._bubble.isVisible(), "DND exit should stay silent")
        _assert(
            widget._last_lifecycle_line == "",
            "DND exit should not pick a farewell line",
        )
    finally:
        widget._timer.stop()


def main():
    from PySide6.QtWidgets import QApplication

    import main as maid_main

    QApplication.instance() or QApplication([])
    with tempfile.TemporaryDirectory(prefix="deskmaid-idle-quips-") as tmp_dir:
        os.environ["MAID_APP_STATE_PATH"] = str(Path(tmp_dir) / "app_state.json")
        os.environ["MAID_BUDGET_STATE_PATH"] = str(Path(tmp_dir) / "budget_state.json")
        os.environ["MAID_OUTING_STATE_PATH"] = str(Path(tmp_dir) / "outing_state.json")
        maid_main.HAVE_AUTO_DND_NATIVE_NOTIFICATIONS = False

        test_idle_quip_gating(maid_main)
        test_idle_quip_fires_and_throttles(maid_main)
        test_launch_line(maid_main)
        test_farewell_line(maid_main)
        test_farewell_suppressed_under_dnd(maid_main)
    print("ok")


if __name__ == "__main__":
    main()
